name: Upload Python Package

on:
  # Trigger the workflow when a GitHub Release is published
  release:
    types: [published]

# Minimal global permissions
permissions:
  contents: read          # needed for checkout and artifact download
  id-token: write         # required for PyPI Trusted Publishing via OIDC

jobs:
  build:
    name: Build distributions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'   # pin the toolchain for reproducibility
          cache: pip               # speed up subsequent runs

      - name: Install build backend
        run: python -m pip install --upgrade build

      - name: Build sdist and wheel
        run: python -m build --sdist --wheel

      - name: Run twine check (optional but recommended)
        run: |
          python -m pip install --upgrade twine
          twine check dist/*

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build

    # Protected environment (create it under repo Settings → Environments)
    environment:
      name: pypi
      url: https://pypi.org/project/promptify-ai/

    steps:
      - name: Download dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish via Trusted Publishing
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          # skip-existing: true   # Uncomment to ignore already uploaded versions